return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    ensure_installed = {
        "astro",
        -- "arduino",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cmake",
        "commonlisp",
        "cpp",
        "css",
        "dockerfile",
        -- "elixir",
        -- "elm",
        -- "erlang",
        -- "fennel",
        -- "gleam",
        "go",
        -- "graphql",
        -- "haskell",
        "html",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        -- "julia",
        -- "kotlin",
        -- "latex",
        -- "llvm",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        -- "meson",
        -- "nginx",
        -- "ninja",
        -- "nix",
        -- "ocaml",
        -- "odin",
        -- "php",
        -- "powershell",
        "python",
        -- "qmldir",
        -- "qmljs",
        "racket",
        "regex",
        -- "ruby",
        "rust",
        -- "scala",
        "regex",
        "sql",
        "svelte",
        -- "swift",
        "tmux",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
        "zig",
    },
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = { "ruby" },
    },
    indent = { enable = true, disable = { "ruby" } },
}
